version: 2.0
jobs:
  dockerize:
    machine: true
    steps:
      - attach_workspace:
          at: .
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run: docker build -t $DOCKER_USER/myapp:$CIRCLE_SHA1 .
      - run: docker push $DOCKER_USER/myapp:$CIRCLE_SHA1
      - run: docker push $DOCKER_USER/circle-ci-workshop:latest
  test:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run:
          name: test
          command: 
            gradle test          
      - store_test_results:
          path: build/test-results   
      - persist_to_workspace:
          root: .
          paths: 
            - .              
  package:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - attach_workspace:
          at: .
      - run:
          name: package
          command:
            gradle jar
      - store_artifacts:
          path: build/libs
          destination: build
      - persist_to_workspace:
          root: .
          paths: 
            - build/libs
workflows:
  version: 2
  two_job_flow:
    jobs:
      - test
      - package:
        requires:
          - test
      - dockerize
        requires:
          - package


   