version: 2.0
jobs:
  test:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run:
          name: test
          command: 
            gradle test          
      - store_test_results:
          path: build/test-results                 
  package:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run:
          name: package
          command:
            gradle jar
      - store_artifacts:
          path: build/libs
          destination: prefix
      - attach_workspace:
            at: /tmp/workspace
workflows:
  version: 2
  two_job_flow:
    jobs:
      - test
      - package
   